### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by limzx0307** [limzx0307/ponggame.github.io#1]
Add new feature

## TODO

- [ ] Add more styling
- [ ] Add a score limit and make few rounds of game (Like 5 score each game and 3 win 2)
- [ ] Add a score history
